/*
 * Blog API
 *
 * This is a blog API
 *
 * API version: 1.0.0
 * Contact: dzenancindrak@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"context"
	"log"
	"net/http"
	"os"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/go"
	//
	sw "github.com/DzeCin/blog-backend/go"

	"github.com/joho/godotenv"
)

func main() {
	var (
		username     string
		password     string
		databaseHost string
		databaseName string
	)

	if len(os.Getenv("DEV")) != 0 {
		err := godotenv.Load(".development.env")
		if err != nil {
			log.Fatal("Error loading .env file")
		}
	}

	username = os.Getenv("DB_USERNAME")
	password = os.Getenv("DB_PASSWORD")
	databaseHost = os.Getenv("DB_HOST")
	databaseName = os.Getenv("DB_NAME")

	log.Printf("Server started")

	DBkey := "db"

	// create db client

	client := sw.NewDatabaseCLI(username, password, databaseHost, databaseName)

	var ctx context.Context

	ctx = context.Background()

	ctx = context.WithValue(ctx, DBkey, client)

	router := sw.NewRouter(&ctx)

	log.Fatal(http.ListenAndServe(":8080", router))
}
