/*
 * Blog API
 *
 * This is a blog API
 *
 * API version: 1.0.0
 * Contact: dzenancindrak@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package blog

type Post struct {
	Id string `json:"id" bson:"_id" validate:"required|uuid"`

	Title string `json:"title" bson:"title" validate:"required"`

	Tags []string `json:"tags" bson:"tags"`

	Header string `json:"header" bson:"header" validate:"required"`

	Content string `json:"content" bson:"content" validate:"required"`

	Author string `json:"author" bson:"author" validate:"required"`

	DateCreated string `json:"dateCreated" bson:"dateCreated" validate:"required"`

	DateUpdated string `json:"dateUpdated" bson:"dateUpdated" validate:"required"`
}
