/*
 * Blog API
 *
 * This is a blog API
 *
 * API version: 1.0.0
 * Contact: dzenancindrak@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package blog

import (
	"context"
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name           string
	Methods        []string
	Pattern        string
	EnabledAuth    bool
	ctxHandlerFunc ctxHandler
}

type Routes []Route

type ctxHandler func(w http.ResponseWriter, r *http.Request, ctx *context.Context)

func ContextHandler(handler ctxHandler, ctx *context.Context) func(w http.ResponseWriter, r *http.Request) {
	return func(w http.ResponseWriter, r *http.Request) {
		corsHeaders(&w)
		handler(w, r, ctx)
	}
}

func corsHeaders(w *http.ResponseWriter) {

	(*w).Header().Set("Access-Control-Allow-Origin", "*")
	(*w).Header().Set("Access-Control-Allow-Headers", "*")
	(*w).Header().Set("Access-Control-Allow-Methods", "*")

}

func HandleAuthorization(handler ctxHandler, ctx *context.Context) func(w http.ResponseWriter, r *http.Request) {
	return func(w http.ResponseWriter, r *http.Request) {
		corsHeaders(&w)

		var claims *Claims
		var isAllowed bool

		claims = GetUserClaims(r.Header.Get("Authorization"))

		for _, elmt := range (*claims).Roles {
			if elmt == "0362b96d-a505-4462-a040-2b7ca87c6f81" {
				isAllowed = true
				fmt.Println("IsAllowed")
			}
		}

		if isAllowed {
			handler(w, r, ctx)
		} else {
			w.WriteHeader(http.StatusUnauthorized)
		}
	}
}

func NewRouter(ctx *context.Context) *mux.Router {
	router := mux.NewRouter().StrictSlash(true)

	for _, route := range routes {
		var contHandler ctxHandler
		var handler http.Handler
		contHandler = route.ctxHandlerFunc
		if route.EnabledAuth {
			handler = http.HandlerFunc(HandleAuthorization(contHandler, ctx))
		} else {
			handler = http.HandlerFunc(ContextHandler(contHandler, ctx))
		}

		handler = Logger(handler, route.Name)

		router.
			Methods(route.Methods...).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

var routes = Routes{
	Route{
		"HealthCheck",
		[]string{strings.ToUpper("Get"), strings.ToUpper("Options")},
		"/",
		false,
		HealthCheck,
	},

	Route{
		"AddPost",
		[]string{strings.ToUpper("Post")},
		"/posts",
		true,
		AddPost,
	},

	Route{
		"DeletePost",
		[]string{strings.ToUpper("Delete")},
		"/posts/{postId}",
		true,
		DeletePost,
	},

	Route{
		"GetPost",
		[]string{strings.ToUpper("Get"), strings.ToUpper("Options")},
		"/posts/{postId}",
		false,
		GetPost,
	},

	Route{
		"GetPosts",
		[]string{strings.ToUpper("Get"), strings.ToUpper("Options")},
		"/posts",
		false,
		GetPosts,
	},

	Route{
		"UpdatePost",
		[]string{strings.ToUpper("Patch")},
		"/posts/{postId}",
		true,
		UpdatePost,
	},
}
